// Generated by CoffeeScript 1.6.3
(function() {
  var $, AES, App, Backbone, app;

  $ = require("jquery");

  Backbone = require("backbone");

  AES = require("Gibberish-AES");

  App = Backbone.View.extend({
    el: ".app",
    events: {
      "submit .open form": "open"
    },
    initialize: function() {
      return this.safe = AES.enc(JSON.stringify([
        {
          name: "value"
        }
      ]), "password");
    },
    open: function(e) {
      e.preventDefault();
      return console.log(AES.dec(this.safe, this.$(".open input[type=password]").val()));
    }
  });

  app = new App();

}).call(this);
